### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by aleksmend** [GiddyLinux/craiyon-bot#2]
How to fix it? After request - Error

Requesting  tree
Ignoring exception in on_message
Traceback (most recent call last):
  File "B:\pythonProject6\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "B:\pythonProject6\craiyon-bot\main.py", line 48, in on_message
    await message.reply(file=discord.File(file_name))
  File "B:\pythonProject6\lib\site-packages\discord\file.py", line 73, in __init__
    self.fp = open(fp, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'images/183070.jpg'

**Comment by lol219** [comment]
Welp

**Comment by lol219** [comment]
Create it

**Comment by aleksmend** [comment]
> Create it

Create what? THere is no image folder or smthing in that project

**Comment by tony-mall** [comment]
Hi I am aware of this issue,

im am planning to fix it soon
